// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/code.proto

package clarifai2.internal.grpc.api;

public final class Code {
  private Code() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetStatusCodeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:clarifai.api.GetStatusCodeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string status_code_id = 1;</code>
     */
    java.lang.String getStatusCodeId();
    /**
     * <code>string status_code_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getStatusCodeIdBytes();
  }
  /**
   * Protobuf type {@code clarifai.api.GetStatusCodeRequest}
   */
  public  static final class GetStatusCodeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:clarifai.api.GetStatusCodeRequest)
      GetStatusCodeRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetStatusCodeRequest.newBuilder() to construct.
    private GetStatusCodeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetStatusCodeRequest() {
      statusCodeId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetStatusCodeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              statusCodeId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_GetStatusCodeRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_GetStatusCodeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              clarifai2.internal.grpc.api.Code.GetStatusCodeRequest.class, clarifai2.internal.grpc.api.Code.GetStatusCodeRequest.Builder.class);
    }

    public static final int STATUS_CODE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object statusCodeId_;
    /**
     * <code>string status_code_id = 1;</code>
     */
    public java.lang.String getStatusCodeId() {
      java.lang.Object ref = statusCodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statusCodeId_ = s;
        return s;
      }
    }
    /**
     * <code>string status_code_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStatusCodeIdBytes() {
      java.lang.Object ref = statusCodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statusCodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStatusCodeIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, statusCodeId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStatusCodeIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, statusCodeId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof clarifai2.internal.grpc.api.Code.GetStatusCodeRequest)) {
        return super.equals(obj);
      }
      clarifai2.internal.grpc.api.Code.GetStatusCodeRequest other = (clarifai2.internal.grpc.api.Code.GetStatusCodeRequest) obj;

      boolean result = true;
      result = result && getStatusCodeId()
          .equals(other.getStatusCodeId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_CODE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getStatusCodeId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static clarifai2.internal.grpc.api.Code.GetStatusCodeRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.Code.GetStatusCodeRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.GetStatusCodeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.Code.GetStatusCodeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.GetStatusCodeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.Code.GetStatusCodeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.GetStatusCodeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.Code.GetStatusCodeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.GetStatusCodeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.Code.GetStatusCodeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.GetStatusCodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.Code.GetStatusCodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(clarifai2.internal.grpc.api.Code.GetStatusCodeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code clarifai.api.GetStatusCodeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:clarifai.api.GetStatusCodeRequest)
        clarifai2.internal.grpc.api.Code.GetStatusCodeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_GetStatusCodeRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_GetStatusCodeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                clarifai2.internal.grpc.api.Code.GetStatusCodeRequest.class, clarifai2.internal.grpc.api.Code.GetStatusCodeRequest.Builder.class);
      }

      // Construct using clarifai2.internal.grpc.api.Code.GetStatusCodeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        statusCodeId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_GetStatusCodeRequest_descriptor;
      }

      public clarifai2.internal.grpc.api.Code.GetStatusCodeRequest getDefaultInstanceForType() {
        return clarifai2.internal.grpc.api.Code.GetStatusCodeRequest.getDefaultInstance();
      }

      public clarifai2.internal.grpc.api.Code.GetStatusCodeRequest build() {
        clarifai2.internal.grpc.api.Code.GetStatusCodeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public clarifai2.internal.grpc.api.Code.GetStatusCodeRequest buildPartial() {
        clarifai2.internal.grpc.api.Code.GetStatusCodeRequest result = new clarifai2.internal.grpc.api.Code.GetStatusCodeRequest(this);
        result.statusCodeId_ = statusCodeId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof clarifai2.internal.grpc.api.Code.GetStatusCodeRequest) {
          return mergeFrom((clarifai2.internal.grpc.api.Code.GetStatusCodeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(clarifai2.internal.grpc.api.Code.GetStatusCodeRequest other) {
        if (other == clarifai2.internal.grpc.api.Code.GetStatusCodeRequest.getDefaultInstance()) return this;
        if (!other.getStatusCodeId().isEmpty()) {
          statusCodeId_ = other.statusCodeId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        clarifai2.internal.grpc.api.Code.GetStatusCodeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (clarifai2.internal.grpc.api.Code.GetStatusCodeRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object statusCodeId_ = "";
      /**
       * <code>string status_code_id = 1;</code>
       */
      public java.lang.String getStatusCodeId() {
        java.lang.Object ref = statusCodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          statusCodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status_code_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStatusCodeIdBytes() {
        java.lang.Object ref = statusCodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          statusCodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status_code_id = 1;</code>
       */
      public Builder setStatusCodeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        statusCodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status_code_id = 1;</code>
       */
      public Builder clearStatusCodeId() {
        
        statusCodeId_ = getDefaultInstance().getStatusCodeId();
        onChanged();
        return this;
      }
      /**
       * <code>string status_code_id = 1;</code>
       */
      public Builder setStatusCodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        statusCodeId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:clarifai.api.GetStatusCodeRequest)
    }

    // @@protoc_insertion_point(class_scope:clarifai.api.GetStatusCodeRequest)
    private static final clarifai2.internal.grpc.api.Code.GetStatusCodeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new clarifai2.internal.grpc.api.Code.GetStatusCodeRequest();
    }

    public static clarifai2.internal.grpc.api.Code.GetStatusCodeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetStatusCodeRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetStatusCodeRequest>() {
      public GetStatusCodeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetStatusCodeRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetStatusCodeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetStatusCodeRequest> getParserForType() {
      return PARSER;
    }

    public clarifai2.internal.grpc.api.Code.GetStatusCodeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListStatusCodesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:clarifai.api.ListStatusCodesRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code clarifai.api.ListStatusCodesRequest}
   */
  public  static final class ListStatusCodesRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:clarifai.api.ListStatusCodesRequest)
      ListStatusCodesRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ListStatusCodesRequest.newBuilder() to construct.
    private ListStatusCodesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListStatusCodesRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ListStatusCodesRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_ListStatusCodesRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_ListStatusCodesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              clarifai2.internal.grpc.api.Code.ListStatusCodesRequest.class, clarifai2.internal.grpc.api.Code.ListStatusCodesRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof clarifai2.internal.grpc.api.Code.ListStatusCodesRequest)) {
        return super.equals(obj);
      }
      clarifai2.internal.grpc.api.Code.ListStatusCodesRequest other = (clarifai2.internal.grpc.api.Code.ListStatusCodesRequest) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static clarifai2.internal.grpc.api.Code.ListStatusCodesRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.Code.ListStatusCodesRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.ListStatusCodesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.Code.ListStatusCodesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.ListStatusCodesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.Code.ListStatusCodesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.ListStatusCodesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.Code.ListStatusCodesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.ListStatusCodesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.Code.ListStatusCodesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.ListStatusCodesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.Code.ListStatusCodesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(clarifai2.internal.grpc.api.Code.ListStatusCodesRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code clarifai.api.ListStatusCodesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:clarifai.api.ListStatusCodesRequest)
        clarifai2.internal.grpc.api.Code.ListStatusCodesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_ListStatusCodesRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_ListStatusCodesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                clarifai2.internal.grpc.api.Code.ListStatusCodesRequest.class, clarifai2.internal.grpc.api.Code.ListStatusCodesRequest.Builder.class);
      }

      // Construct using clarifai2.internal.grpc.api.Code.ListStatusCodesRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_ListStatusCodesRequest_descriptor;
      }

      public clarifai2.internal.grpc.api.Code.ListStatusCodesRequest getDefaultInstanceForType() {
        return clarifai2.internal.grpc.api.Code.ListStatusCodesRequest.getDefaultInstance();
      }

      public clarifai2.internal.grpc.api.Code.ListStatusCodesRequest build() {
        clarifai2.internal.grpc.api.Code.ListStatusCodesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public clarifai2.internal.grpc.api.Code.ListStatusCodesRequest buildPartial() {
        clarifai2.internal.grpc.api.Code.ListStatusCodesRequest result = new clarifai2.internal.grpc.api.Code.ListStatusCodesRequest(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof clarifai2.internal.grpc.api.Code.ListStatusCodesRequest) {
          return mergeFrom((clarifai2.internal.grpc.api.Code.ListStatusCodesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(clarifai2.internal.grpc.api.Code.ListStatusCodesRequest other) {
        if (other == clarifai2.internal.grpc.api.Code.ListStatusCodesRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        clarifai2.internal.grpc.api.Code.ListStatusCodesRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (clarifai2.internal.grpc.api.Code.ListStatusCodesRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:clarifai.api.ListStatusCodesRequest)
    }

    // @@protoc_insertion_point(class_scope:clarifai.api.ListStatusCodesRequest)
    private static final clarifai2.internal.grpc.api.Code.ListStatusCodesRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new clarifai2.internal.grpc.api.Code.ListStatusCodesRequest();
    }

    public static clarifai2.internal.grpc.api.Code.ListStatusCodesRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListStatusCodesRequest>
        PARSER = new com.google.protobuf.AbstractParser<ListStatusCodesRequest>() {
      public ListStatusCodesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListStatusCodesRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ListStatusCodesRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListStatusCodesRequest> getParserForType() {
      return PARSER;
    }

    public clarifai2.internal.grpc.api.Code.ListStatusCodesRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SingleStatusCodeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:clarifai.api.SingleStatusCodeResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    clarifai2.internal.grpc.api.status.StatusOuterClass.Status getStatus();
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder getStatusOrBuilder();
  }
  /**
   * Protobuf type {@code clarifai.api.SingleStatusCodeResponse}
   */
  public  static final class SingleStatusCodeResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:clarifai.api.SingleStatusCodeResponse)
      SingleStatusCodeResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SingleStatusCodeResponse.newBuilder() to construct.
    private SingleStatusCodeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SingleStatusCodeResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SingleStatusCodeResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder subBuilder = null;
              if (status_ != null) {
                subBuilder = status_.toBuilder();
              }
              status_ = input.readMessage(clarifai2.internal.grpc.api.status.StatusOuterClass.Status.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(status_);
                status_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_SingleStatusCodeResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_SingleStatusCodeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse.class, clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private clarifai2.internal.grpc.api.status.StatusOuterClass.Status status_;
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    public boolean hasStatus() {
      return status_ != null;
    }
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    public clarifai2.internal.grpc.api.status.StatusOuterClass.Status getStatus() {
      return status_ == null ? clarifai2.internal.grpc.api.status.StatusOuterClass.Status.getDefaultInstance() : status_;
    }
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    public clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder getStatusOrBuilder() {
      return getStatus();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != null) {
        output.writeMessage(1, getStatus());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStatus());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse)) {
        return super.equals(obj);
      }
      clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse other = (clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse) obj;

      boolean result = true;
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && getStatus()
            .equals(other.getStatus());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code clarifai.api.SingleStatusCodeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:clarifai.api.SingleStatusCodeResponse)
        clarifai2.internal.grpc.api.Code.SingleStatusCodeResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_SingleStatusCodeResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_SingleStatusCodeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse.class, clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse.Builder.class);
      }

      // Construct using clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (statusBuilder_ == null) {
          status_ = null;
        } else {
          status_ = null;
          statusBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_SingleStatusCodeResponse_descriptor;
      }

      public clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse getDefaultInstanceForType() {
        return clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse.getDefaultInstance();
      }

      public clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse build() {
        clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse buildPartial() {
        clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse result = new clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse(this);
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse) {
          return mergeFrom((clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse other) {
        if (other == clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          mergeStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private clarifai2.internal.grpc.api.status.StatusOuterClass.Status status_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          clarifai2.internal.grpc.api.status.StatusOuterClass.Status, clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder, clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder> statusBuilder_;
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public boolean hasStatus() {
        return statusBuilder_ != null || status_ != null;
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public clarifai2.internal.grpc.api.status.StatusOuterClass.Status getStatus() {
        if (statusBuilder_ == null) {
          return status_ == null ? clarifai2.internal.grpc.api.status.StatusOuterClass.Status.getDefaultInstance() : status_;
        } else {
          return statusBuilder_.getMessage();
        }
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public Builder setStatus(clarifai2.internal.grpc.api.status.StatusOuterClass.Status value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
          onChanged();
        } else {
          statusBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public Builder setStatus(
          clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder builderForValue) {
        if (statusBuilder_ == null) {
          status_ = builderForValue.build();
          onChanged();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public Builder mergeStatus(clarifai2.internal.grpc.api.status.StatusOuterClass.Status value) {
        if (statusBuilder_ == null) {
          if (status_ != null) {
            status_ =
              clarifai2.internal.grpc.api.status.StatusOuterClass.Status.newBuilder(status_).mergeFrom(value).buildPartial();
          } else {
            status_ = value;
          }
          onChanged();
        } else {
          statusBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          status_ = null;
          onChanged();
        } else {
          status_ = null;
          statusBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder getStatusBuilder() {
        
        onChanged();
        return getStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder getStatusOrBuilder() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          return status_ == null ?
              clarifai2.internal.grpc.api.status.StatusOuterClass.Status.getDefaultInstance() : status_;
        }
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          clarifai2.internal.grpc.api.status.StatusOuterClass.Status, clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder, clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder> 
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              clarifai2.internal.grpc.api.status.StatusOuterClass.Status, clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder, clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder>(
                  getStatus(),
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:clarifai.api.SingleStatusCodeResponse)
    }

    // @@protoc_insertion_point(class_scope:clarifai.api.SingleStatusCodeResponse)
    private static final clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse();
    }

    public static clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SingleStatusCodeResponse>
        PARSER = new com.google.protobuf.AbstractParser<SingleStatusCodeResponse>() {
      public SingleStatusCodeResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SingleStatusCodeResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SingleStatusCodeResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SingleStatusCodeResponse> getParserForType() {
      return PARSER;
    }

    public clarifai2.internal.grpc.api.Code.SingleStatusCodeResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MultiStatusCodeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:clarifai.api.MultiStatusCodeResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    clarifai2.internal.grpc.api.status.StatusOuterClass.Status getStatus();
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder getStatusOrBuilder();

    /**
     * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
     */
    java.util.List<clarifai2.internal.grpc.api.status.StatusOuterClass.Status> 
        getStatusesList();
    /**
     * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
     */
    clarifai2.internal.grpc.api.status.StatusOuterClass.Status getStatuses(int index);
    /**
     * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
     */
    int getStatusesCount();
    /**
     * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
     */
    java.util.List<? extends clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder> 
        getStatusesOrBuilderList();
    /**
     * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
     */
    clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder getStatusesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code clarifai.api.MultiStatusCodeResponse}
   */
  public  static final class MultiStatusCodeResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:clarifai.api.MultiStatusCodeResponse)
      MultiStatusCodeResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MultiStatusCodeResponse.newBuilder() to construct.
    private MultiStatusCodeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultiStatusCodeResponse() {
      statuses_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultiStatusCodeResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder subBuilder = null;
              if (status_ != null) {
                subBuilder = status_.toBuilder();
              }
              status_ = input.readMessage(clarifai2.internal.grpc.api.status.StatusOuterClass.Status.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(status_);
                status_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                statuses_ = new java.util.ArrayList<clarifai2.internal.grpc.api.status.StatusOuterClass.Status>();
                mutable_bitField0_ |= 0x00000002;
              }
              statuses_.add(
                  input.readMessage(clarifai2.internal.grpc.api.status.StatusOuterClass.Status.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          statuses_ = java.util.Collections.unmodifiableList(statuses_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_MultiStatusCodeResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_MultiStatusCodeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse.class, clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse.Builder.class);
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private clarifai2.internal.grpc.api.status.StatusOuterClass.Status status_;
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    public boolean hasStatus() {
      return status_ != null;
    }
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    public clarifai2.internal.grpc.api.status.StatusOuterClass.Status getStatus() {
      return status_ == null ? clarifai2.internal.grpc.api.status.StatusOuterClass.Status.getDefaultInstance() : status_;
    }
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    public clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder getStatusOrBuilder() {
      return getStatus();
    }

    public static final int STATUSES_FIELD_NUMBER = 2;
    private java.util.List<clarifai2.internal.grpc.api.status.StatusOuterClass.Status> statuses_;
    /**
     * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
     */
    public java.util.List<clarifai2.internal.grpc.api.status.StatusOuterClass.Status> getStatusesList() {
      return statuses_;
    }
    /**
     * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
     */
    public java.util.List<? extends clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder> 
        getStatusesOrBuilderList() {
      return statuses_;
    }
    /**
     * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
     */
    public int getStatusesCount() {
      return statuses_.size();
    }
    /**
     * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
     */
    public clarifai2.internal.grpc.api.status.StatusOuterClass.Status getStatuses(int index) {
      return statuses_.get(index);
    }
    /**
     * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
     */
    public clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder getStatusesOrBuilder(
        int index) {
      return statuses_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != null) {
        output.writeMessage(1, getStatus());
      }
      for (int i = 0; i < statuses_.size(); i++) {
        output.writeMessage(2, statuses_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStatus());
      }
      for (int i = 0; i < statuses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, statuses_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse)) {
        return super.equals(obj);
      }
      clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse other = (clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse) obj;

      boolean result = true;
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && getStatus()
            .equals(other.getStatus());
      }
      result = result && getStatusesList()
          .equals(other.getStatusesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus().hashCode();
      }
      if (getStatusesCount() > 0) {
        hash = (37 * hash) + STATUSES_FIELD_NUMBER;
        hash = (53 * hash) + getStatusesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code clarifai.api.MultiStatusCodeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:clarifai.api.MultiStatusCodeResponse)
        clarifai2.internal.grpc.api.Code.MultiStatusCodeResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_MultiStatusCodeResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_MultiStatusCodeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse.class, clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse.Builder.class);
      }

      // Construct using clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStatusesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (statusBuilder_ == null) {
          status_ = null;
        } else {
          status_ = null;
          statusBuilder_ = null;
        }
        if (statusesBuilder_ == null) {
          statuses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          statusesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return clarifai2.internal.grpc.api.Code.internal_static_clarifai_api_MultiStatusCodeResponse_descriptor;
      }

      public clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse getDefaultInstanceForType() {
        return clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse.getDefaultInstance();
      }

      public clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse build() {
        clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse buildPartial() {
        clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse result = new clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        if (statusesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            statuses_ = java.util.Collections.unmodifiableList(statuses_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.statuses_ = statuses_;
        } else {
          result.statuses_ = statusesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse) {
          return mergeFrom((clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse other) {
        if (other == clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          mergeStatus(other.getStatus());
        }
        if (statusesBuilder_ == null) {
          if (!other.statuses_.isEmpty()) {
            if (statuses_.isEmpty()) {
              statuses_ = other.statuses_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureStatusesIsMutable();
              statuses_.addAll(other.statuses_);
            }
            onChanged();
          }
        } else {
          if (!other.statuses_.isEmpty()) {
            if (statusesBuilder_.isEmpty()) {
              statusesBuilder_.dispose();
              statusesBuilder_ = null;
              statuses_ = other.statuses_;
              bitField0_ = (bitField0_ & ~0x00000002);
              statusesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStatusesFieldBuilder() : null;
            } else {
              statusesBuilder_.addAllMessages(other.statuses_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private clarifai2.internal.grpc.api.status.StatusOuterClass.Status status_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          clarifai2.internal.grpc.api.status.StatusOuterClass.Status, clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder, clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder> statusBuilder_;
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public boolean hasStatus() {
        return statusBuilder_ != null || status_ != null;
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public clarifai2.internal.grpc.api.status.StatusOuterClass.Status getStatus() {
        if (statusBuilder_ == null) {
          return status_ == null ? clarifai2.internal.grpc.api.status.StatusOuterClass.Status.getDefaultInstance() : status_;
        } else {
          return statusBuilder_.getMessage();
        }
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public Builder setStatus(clarifai2.internal.grpc.api.status.StatusOuterClass.Status value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
          onChanged();
        } else {
          statusBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public Builder setStatus(
          clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder builderForValue) {
        if (statusBuilder_ == null) {
          status_ = builderForValue.build();
          onChanged();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public Builder mergeStatus(clarifai2.internal.grpc.api.status.StatusOuterClass.Status value) {
        if (statusBuilder_ == null) {
          if (status_ != null) {
            status_ =
              clarifai2.internal.grpc.api.status.StatusOuterClass.Status.newBuilder(status_).mergeFrom(value).buildPartial();
          } else {
            status_ = value;
          }
          onChanged();
        } else {
          statusBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          status_ = null;
          onChanged();
        } else {
          status_ = null;
          statusBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder getStatusBuilder() {
        
        onChanged();
        return getStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      public clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder getStatusOrBuilder() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          return status_ == null ?
              clarifai2.internal.grpc.api.status.StatusOuterClass.Status.getDefaultInstance() : status_;
        }
      }
      /**
       * <code>.clarifai.api.status.Status status = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          clarifai2.internal.grpc.api.status.StatusOuterClass.Status, clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder, clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder> 
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              clarifai2.internal.grpc.api.status.StatusOuterClass.Status, clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder, clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder>(
                  getStatus(),
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }

      private java.util.List<clarifai2.internal.grpc.api.status.StatusOuterClass.Status> statuses_ =
        java.util.Collections.emptyList();
      private void ensureStatusesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          statuses_ = new java.util.ArrayList<clarifai2.internal.grpc.api.status.StatusOuterClass.Status>(statuses_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          clarifai2.internal.grpc.api.status.StatusOuterClass.Status, clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder, clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder> statusesBuilder_;

      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public java.util.List<clarifai2.internal.grpc.api.status.StatusOuterClass.Status> getStatusesList() {
        if (statusesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(statuses_);
        } else {
          return statusesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public int getStatusesCount() {
        if (statusesBuilder_ == null) {
          return statuses_.size();
        } else {
          return statusesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public clarifai2.internal.grpc.api.status.StatusOuterClass.Status getStatuses(int index) {
        if (statusesBuilder_ == null) {
          return statuses_.get(index);
        } else {
          return statusesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public Builder setStatuses(
          int index, clarifai2.internal.grpc.api.status.StatusOuterClass.Status value) {
        if (statusesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatusesIsMutable();
          statuses_.set(index, value);
          onChanged();
        } else {
          statusesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public Builder setStatuses(
          int index, clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder builderForValue) {
        if (statusesBuilder_ == null) {
          ensureStatusesIsMutable();
          statuses_.set(index, builderForValue.build());
          onChanged();
        } else {
          statusesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public Builder addStatuses(clarifai2.internal.grpc.api.status.StatusOuterClass.Status value) {
        if (statusesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatusesIsMutable();
          statuses_.add(value);
          onChanged();
        } else {
          statusesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public Builder addStatuses(
          int index, clarifai2.internal.grpc.api.status.StatusOuterClass.Status value) {
        if (statusesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatusesIsMutable();
          statuses_.add(index, value);
          onChanged();
        } else {
          statusesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public Builder addStatuses(
          clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder builderForValue) {
        if (statusesBuilder_ == null) {
          ensureStatusesIsMutable();
          statuses_.add(builderForValue.build());
          onChanged();
        } else {
          statusesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public Builder addStatuses(
          int index, clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder builderForValue) {
        if (statusesBuilder_ == null) {
          ensureStatusesIsMutable();
          statuses_.add(index, builderForValue.build());
          onChanged();
        } else {
          statusesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public Builder addAllStatuses(
          java.lang.Iterable<? extends clarifai2.internal.grpc.api.status.StatusOuterClass.Status> values) {
        if (statusesBuilder_ == null) {
          ensureStatusesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, statuses_);
          onChanged();
        } else {
          statusesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public Builder clearStatuses() {
        if (statusesBuilder_ == null) {
          statuses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          statusesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public Builder removeStatuses(int index) {
        if (statusesBuilder_ == null) {
          ensureStatusesIsMutable();
          statuses_.remove(index);
          onChanged();
        } else {
          statusesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder getStatusesBuilder(
          int index) {
        return getStatusesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder getStatusesOrBuilder(
          int index) {
        if (statusesBuilder_ == null) {
          return statuses_.get(index);  } else {
          return statusesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public java.util.List<? extends clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder> 
           getStatusesOrBuilderList() {
        if (statusesBuilder_ != null) {
          return statusesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(statuses_);
        }
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder addStatusesBuilder() {
        return getStatusesFieldBuilder().addBuilder(
            clarifai2.internal.grpc.api.status.StatusOuterClass.Status.getDefaultInstance());
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder addStatusesBuilder(
          int index) {
        return getStatusesFieldBuilder().addBuilder(
            index, clarifai2.internal.grpc.api.status.StatusOuterClass.Status.getDefaultInstance());
      }
      /**
       * <code>repeated .clarifai.api.status.Status statuses = 2;</code>
       */
      public java.util.List<clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder> 
           getStatusesBuilderList() {
        return getStatusesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          clarifai2.internal.grpc.api.status.StatusOuterClass.Status, clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder, clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder> 
          getStatusesFieldBuilder() {
        if (statusesBuilder_ == null) {
          statusesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              clarifai2.internal.grpc.api.status.StatusOuterClass.Status, clarifai2.internal.grpc.api.status.StatusOuterClass.Status.Builder, clarifai2.internal.grpc.api.status.StatusOuterClass.StatusOrBuilder>(
                  statuses_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          statuses_ = null;
        }
        return statusesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:clarifai.api.MultiStatusCodeResponse)
    }

    // @@protoc_insertion_point(class_scope:clarifai.api.MultiStatusCodeResponse)
    private static final clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse();
    }

    public static clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultiStatusCodeResponse>
        PARSER = new com.google.protobuf.AbstractParser<MultiStatusCodeResponse>() {
      public MultiStatusCodeResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultiStatusCodeResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultiStatusCodeResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultiStatusCodeResponse> getParserForType() {
      return PARSER;
    }

    public clarifai2.internal.grpc.api.Code.MultiStatusCodeResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clarifai_api_GetStatusCodeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clarifai_api_GetStatusCodeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clarifai_api_ListStatusCodesRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clarifai_api_ListStatusCodesRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clarifai_api_SingleStatusCodeResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clarifai_api_SingleStatusCodeResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clarifai_api_MultiStatusCodeResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clarifai_api_MultiStatusCodeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035proto/clarifai/api/code.proto\022\014clarifa" +
      "i.api\032&proto/clarifai/api/status/status." +
      "proto\".\n\024GetStatusCodeRequest\022\026\n\016status_" +
      "code_id\030\001 \001(\t\"\030\n\026ListStatusCodesRequest\"" +
      "G\n\030SingleStatusCodeResponse\022+\n\006status\030\001 " +
      "\001(\0132\033.clarifai.api.status.Status\"u\n\027Mult" +
      "iStatusCodeResponse\022+\n\006status\030\001 \001(\0132\033.cl" +
      "arifai.api.status.Status\022-\n\010statuses\030\002 \003" +
      "(\0132\033.clarifai.api.status.StatusBA\n\033clari" +
      "fai2.internal.grpc.apiZ\003api\242\002\004CAIP\302\002\001_\312\002" +
      "\021Clarifai\\Internalb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          clarifai2.internal.grpc.api.status.StatusOuterClass.getDescriptor(),
        }, assigner);
    internal_static_clarifai_api_GetStatusCodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_clarifai_api_GetStatusCodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clarifai_api_GetStatusCodeRequest_descriptor,
        new java.lang.String[] { "StatusCodeId", });
    internal_static_clarifai_api_ListStatusCodesRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_clarifai_api_ListStatusCodesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clarifai_api_ListStatusCodesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_clarifai_api_SingleStatusCodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_clarifai_api_SingleStatusCodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clarifai_api_SingleStatusCodeResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_clarifai_api_MultiStatusCodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_clarifai_api_MultiStatusCodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clarifai_api_MultiStatusCodeResponse_descriptor,
        new java.lang.String[] { "Status", "Statuses", });
    clarifai2.internal.grpc.api.status.StatusOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
