// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/concept_graph.proto

package clarifai2.internal.grpc.api;

public final class ConceptGraph {
  private ConceptGraph() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ListConceptRelationsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:clarifai.api.ListConceptRelationsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    boolean hasUserAppId();
    /**
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    clarifai2.internal.grpc.api.Common.UserAppIDSet getUserAppId();
    /**
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    clarifai2.internal.grpc.api.Common.UserAppIDSetOrBuilder getUserAppIdOrBuilder();

    /**
     * <code>string concept_id = 2;</code>
     */
    java.lang.String getConceptId();
    /**
     * <code>string concept_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getConceptIdBytes();

    /**
     * <code>string predicate = 3;</code>
     */
    java.lang.String getPredicate();
    /**
     * <code>string predicate = 3;</code>
     */
    com.google.protobuf.ByteString
        getPredicateBytes();

    /**
     * <code>uint32 page = 4;</code>
     */
    int getPage();

    /**
     * <code>uint32 per_page = 5;</code>
     */
    int getPerPage();
  }
  /**
   * Protobuf type {@code clarifai.api.ListConceptRelationsRequest}
   */
  public  static final class ListConceptRelationsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:clarifai.api.ListConceptRelationsRequest)
      ListConceptRelationsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ListConceptRelationsRequest.newBuilder() to construct.
    private ListConceptRelationsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListConceptRelationsRequest() {
      conceptId_ = "";
      predicate_ = "";
      page_ = 0;
      perPage_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ListConceptRelationsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              clarifai2.internal.grpc.api.Common.UserAppIDSet.Builder subBuilder = null;
              if (userAppId_ != null) {
                subBuilder = userAppId_.toBuilder();
              }
              userAppId_ = input.readMessage(clarifai2.internal.grpc.api.Common.UserAppIDSet.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userAppId_);
                userAppId_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              conceptId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              predicate_ = s;
              break;
            }
            case 32: {

              page_ = input.readUInt32();
              break;
            }
            case 40: {

              perPage_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return clarifai2.internal.grpc.api.ConceptGraph.internal_static_clarifai_api_ListConceptRelationsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return clarifai2.internal.grpc.api.ConceptGraph.internal_static_clarifai_api_ListConceptRelationsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest.class, clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest.Builder.class);
    }

    public static final int USER_APP_ID_FIELD_NUMBER = 1;
    private clarifai2.internal.grpc.api.Common.UserAppIDSet userAppId_;
    /**
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    public boolean hasUserAppId() {
      return userAppId_ != null;
    }
    /**
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    public clarifai2.internal.grpc.api.Common.UserAppIDSet getUserAppId() {
      return userAppId_ == null ? clarifai2.internal.grpc.api.Common.UserAppIDSet.getDefaultInstance() : userAppId_;
    }
    /**
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    public clarifai2.internal.grpc.api.Common.UserAppIDSetOrBuilder getUserAppIdOrBuilder() {
      return getUserAppId();
    }

    public static final int CONCEPT_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object conceptId_;
    /**
     * <code>string concept_id = 2;</code>
     */
    public java.lang.String getConceptId() {
      java.lang.Object ref = conceptId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conceptId_ = s;
        return s;
      }
    }
    /**
     * <code>string concept_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getConceptIdBytes() {
      java.lang.Object ref = conceptId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conceptId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREDICATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object predicate_;
    /**
     * <code>string predicate = 3;</code>
     */
    public java.lang.String getPredicate() {
      java.lang.Object ref = predicate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        predicate_ = s;
        return s;
      }
    }
    /**
     * <code>string predicate = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPredicateBytes() {
      java.lang.Object ref = predicate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        predicate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGE_FIELD_NUMBER = 4;
    private int page_;
    /**
     * <code>uint32 page = 4;</code>
     */
    public int getPage() {
      return page_;
    }

    public static final int PER_PAGE_FIELD_NUMBER = 5;
    private int perPage_;
    /**
     * <code>uint32 per_page = 5;</code>
     */
    public int getPerPage() {
      return perPage_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userAppId_ != null) {
        output.writeMessage(1, getUserAppId());
      }
      if (!getConceptIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, conceptId_);
      }
      if (!getPredicateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, predicate_);
      }
      if (page_ != 0) {
        output.writeUInt32(4, page_);
      }
      if (perPage_ != 0) {
        output.writeUInt32(5, perPage_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userAppId_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUserAppId());
      }
      if (!getConceptIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, conceptId_);
      }
      if (!getPredicateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, predicate_);
      }
      if (page_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, page_);
      }
      if (perPage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, perPage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest)) {
        return super.equals(obj);
      }
      clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest other = (clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest) obj;

      boolean result = true;
      result = result && (hasUserAppId() == other.hasUserAppId());
      if (hasUserAppId()) {
        result = result && getUserAppId()
            .equals(other.getUserAppId());
      }
      result = result && getConceptId()
          .equals(other.getConceptId());
      result = result && getPredicate()
          .equals(other.getPredicate());
      result = result && (getPage()
          == other.getPage());
      result = result && (getPerPage()
          == other.getPerPage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserAppId()) {
        hash = (37 * hash) + USER_APP_ID_FIELD_NUMBER;
        hash = (53 * hash) + getUserAppId().hashCode();
      }
      hash = (37 * hash) + CONCEPT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getConceptId().hashCode();
      hash = (37 * hash) + PREDICATE_FIELD_NUMBER;
      hash = (53 * hash) + getPredicate().hashCode();
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage();
      hash = (37 * hash) + PER_PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPerPage();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code clarifai.api.ListConceptRelationsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:clarifai.api.ListConceptRelationsRequest)
        clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return clarifai2.internal.grpc.api.ConceptGraph.internal_static_clarifai_api_ListConceptRelationsRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return clarifai2.internal.grpc.api.ConceptGraph.internal_static_clarifai_api_ListConceptRelationsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest.class, clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest.Builder.class);
      }

      // Construct using clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (userAppIdBuilder_ == null) {
          userAppId_ = null;
        } else {
          userAppId_ = null;
          userAppIdBuilder_ = null;
        }
        conceptId_ = "";

        predicate_ = "";

        page_ = 0;

        perPage_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return clarifai2.internal.grpc.api.ConceptGraph.internal_static_clarifai_api_ListConceptRelationsRequest_descriptor;
      }

      public clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest getDefaultInstanceForType() {
        return clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest.getDefaultInstance();
      }

      public clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest build() {
        clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest buildPartial() {
        clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest result = new clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest(this);
        if (userAppIdBuilder_ == null) {
          result.userAppId_ = userAppId_;
        } else {
          result.userAppId_ = userAppIdBuilder_.build();
        }
        result.conceptId_ = conceptId_;
        result.predicate_ = predicate_;
        result.page_ = page_;
        result.perPage_ = perPage_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest) {
          return mergeFrom((clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest other) {
        if (other == clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest.getDefaultInstance()) return this;
        if (other.hasUserAppId()) {
          mergeUserAppId(other.getUserAppId());
        }
        if (!other.getConceptId().isEmpty()) {
          conceptId_ = other.conceptId_;
          onChanged();
        }
        if (!other.getPredicate().isEmpty()) {
          predicate_ = other.predicate_;
          onChanged();
        }
        if (other.getPage() != 0) {
          setPage(other.getPage());
        }
        if (other.getPerPage() != 0) {
          setPerPage(other.getPerPage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private clarifai2.internal.grpc.api.Common.UserAppIDSet userAppId_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          clarifai2.internal.grpc.api.Common.UserAppIDSet, clarifai2.internal.grpc.api.Common.UserAppIDSet.Builder, clarifai2.internal.grpc.api.Common.UserAppIDSetOrBuilder> userAppIdBuilder_;
      /**
       * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
       */
      public boolean hasUserAppId() {
        return userAppIdBuilder_ != null || userAppId_ != null;
      }
      /**
       * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
       */
      public clarifai2.internal.grpc.api.Common.UserAppIDSet getUserAppId() {
        if (userAppIdBuilder_ == null) {
          return userAppId_ == null ? clarifai2.internal.grpc.api.Common.UserAppIDSet.getDefaultInstance() : userAppId_;
        } else {
          return userAppIdBuilder_.getMessage();
        }
      }
      /**
       * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
       */
      public Builder setUserAppId(clarifai2.internal.grpc.api.Common.UserAppIDSet value) {
        if (userAppIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userAppId_ = value;
          onChanged();
        } else {
          userAppIdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
       */
      public Builder setUserAppId(
          clarifai2.internal.grpc.api.Common.UserAppIDSet.Builder builderForValue) {
        if (userAppIdBuilder_ == null) {
          userAppId_ = builderForValue.build();
          onChanged();
        } else {
          userAppIdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
       */
      public Builder mergeUserAppId(clarifai2.internal.grpc.api.Common.UserAppIDSet value) {
        if (userAppIdBuilder_ == null) {
          if (userAppId_ != null) {
            userAppId_ =
              clarifai2.internal.grpc.api.Common.UserAppIDSet.newBuilder(userAppId_).mergeFrom(value).buildPartial();
          } else {
            userAppId_ = value;
          }
          onChanged();
        } else {
          userAppIdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
       */
      public Builder clearUserAppId() {
        if (userAppIdBuilder_ == null) {
          userAppId_ = null;
          onChanged();
        } else {
          userAppId_ = null;
          userAppIdBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
       */
      public clarifai2.internal.grpc.api.Common.UserAppIDSet.Builder getUserAppIdBuilder() {
        
        onChanged();
        return getUserAppIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
       */
      public clarifai2.internal.grpc.api.Common.UserAppIDSetOrBuilder getUserAppIdOrBuilder() {
        if (userAppIdBuilder_ != null) {
          return userAppIdBuilder_.getMessageOrBuilder();
        } else {
          return userAppId_ == null ?
              clarifai2.internal.grpc.api.Common.UserAppIDSet.getDefaultInstance() : userAppId_;
        }
      }
      /**
       * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          clarifai2.internal.grpc.api.Common.UserAppIDSet, clarifai2.internal.grpc.api.Common.UserAppIDSet.Builder, clarifai2.internal.grpc.api.Common.UserAppIDSetOrBuilder> 
          getUserAppIdFieldBuilder() {
        if (userAppIdBuilder_ == null) {
          userAppIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              clarifai2.internal.grpc.api.Common.UserAppIDSet, clarifai2.internal.grpc.api.Common.UserAppIDSet.Builder, clarifai2.internal.grpc.api.Common.UserAppIDSetOrBuilder>(
                  getUserAppId(),
                  getParentForChildren(),
                  isClean());
          userAppId_ = null;
        }
        return userAppIdBuilder_;
      }

      private java.lang.Object conceptId_ = "";
      /**
       * <code>string concept_id = 2;</code>
       */
      public java.lang.String getConceptId() {
        java.lang.Object ref = conceptId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          conceptId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string concept_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getConceptIdBytes() {
        java.lang.Object ref = conceptId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          conceptId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string concept_id = 2;</code>
       */
      public Builder setConceptId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        conceptId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string concept_id = 2;</code>
       */
      public Builder clearConceptId() {
        
        conceptId_ = getDefaultInstance().getConceptId();
        onChanged();
        return this;
      }
      /**
       * <code>string concept_id = 2;</code>
       */
      public Builder setConceptIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        conceptId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object predicate_ = "";
      /**
       * <code>string predicate = 3;</code>
       */
      public java.lang.String getPredicate() {
        java.lang.Object ref = predicate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          predicate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string predicate = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPredicateBytes() {
        java.lang.Object ref = predicate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          predicate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string predicate = 3;</code>
       */
      public Builder setPredicate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        predicate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string predicate = 3;</code>
       */
      public Builder clearPredicate() {
        
        predicate_ = getDefaultInstance().getPredicate();
        onChanged();
        return this;
      }
      /**
       * <code>string predicate = 3;</code>
       */
      public Builder setPredicateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        predicate_ = value;
        onChanged();
        return this;
      }

      private int page_ ;
      /**
       * <code>uint32 page = 4;</code>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <code>uint32 page = 4;</code>
       */
      public Builder setPage(int value) {
        
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 page = 4;</code>
       */
      public Builder clearPage() {
        
        page_ = 0;
        onChanged();
        return this;
      }

      private int perPage_ ;
      /**
       * <code>uint32 per_page = 5;</code>
       */
      public int getPerPage() {
        return perPage_;
      }
      /**
       * <code>uint32 per_page = 5;</code>
       */
      public Builder setPerPage(int value) {
        
        perPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 per_page = 5;</code>
       */
      public Builder clearPerPage() {
        
        perPage_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:clarifai.api.ListConceptRelationsRequest)
    }

    // @@protoc_insertion_point(class_scope:clarifai.api.ListConceptRelationsRequest)
    private static final clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest();
    }

    public static clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListConceptRelationsRequest>
        PARSER = new com.google.protobuf.AbstractParser<ListConceptRelationsRequest>() {
      public ListConceptRelationsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListConceptRelationsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ListConceptRelationsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListConceptRelationsRequest> getParserForType() {
      return PARSER;
    }

    public clarifai2.internal.grpc.api.ConceptGraph.ListConceptRelationsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clarifai_api_ListConceptRelationsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clarifai_api_ListConceptRelationsRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&proto/clarifai/api/concept_graph.proto" +
      "\022\014clarifai.api\032\037proto/clarifai/api/commo" +
      "n.proto\032)proto/clarifai/api/utils/extens" +
      "ions.proto\"\225\001\n\033ListConceptRelationsReque" +
      "st\022/\n\013user_app_id\030\001 \001(\0132\032.clarifai.api.U" +
      "serAppIDSet\022\022\n\nconcept_id\030\002 \001(\t\022\021\n\tpredi" +
      "cate\030\003 \001(\t\022\014\n\004page\030\004 \001(\r\022\020\n\010per_page\030\005 \001" +
      "(\rBA\n\033clarifai2.internal.grpc.apiZ\003api\242\002" +
      "\004CAIP\302\002\001_\312\002\021Clarifai\\Internalb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          clarifai2.internal.grpc.api.Common.getDescriptor(),
          clarifai2.internal.grpc.api.utils.Extensions.getDescriptor(),
        }, assigner);
    internal_static_clarifai_api_ListConceptRelationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_clarifai_api_ListConceptRelationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clarifai_api_ListConceptRelationsRequest_descriptor,
        new java.lang.String[] { "UserAppId", "ConceptId", "Predicate", "Page", "PerPage", });
    clarifai2.internal.grpc.api.Common.getDescriptor();
    clarifai2.internal.grpc.api.utils.Extensions.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
