// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/feedback.proto

package clarifai2.internal.grpc.api;

public final class Feedback {
  private Feedback() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code clarifai.api.EventType}
   */
  public enum EventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>undefined = 0;</code>
     */
    undefined(0),
    /**
     * <code>search_click = 1;</code>
     */
    search_click(1),
    /**
     * <code>annotation = 2;</code>
     */
    annotation(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>undefined = 0;</code>
     */
    public static final int undefined_VALUE = 0;
    /**
     * <code>search_click = 1;</code>
     */
    public static final int search_click_VALUE = 1;
    /**
     * <code>annotation = 2;</code>
     */
    public static final int annotation_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return undefined;
        case 1: return search_click;
        case 2: return annotation;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return clarifai2.internal.grpc.api.Feedback.getDescriptor().getEnumTypes().get(0);
    }

    private static final EventType[] VALUES = values();

    public static EventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:clarifai.api.EventType)
  }

  public interface FeedbackInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:clarifai.api.FeedbackInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string end_user_id = 1;</code>
     */
    java.lang.String getEndUserId();
    /**
     * <code>string end_user_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getEndUserIdBytes();

    /**
     * <code>string session_id = 2;</code>
     */
    java.lang.String getSessionId();
    /**
     * <code>string session_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <code>.clarifai.api.EventType event_type = 3;</code>
     */
    int getEventTypeValue();
    /**
     * <code>.clarifai.api.EventType event_type = 3;</code>
     */
    clarifai2.internal.grpc.api.Feedback.EventType getEventType();

    /**
     * <code>string output_id = 4;</code>
     */
    java.lang.String getOutputId();
    /**
     * <code>string output_id = 4;</code>
     */
    com.google.protobuf.ByteString
        getOutputIdBytes();

    /**
     * <code>string search_id = 5;</code>
     */
    java.lang.String getSearchId();
    /**
     * <code>string search_id = 5;</code>
     */
    com.google.protobuf.ByteString
        getSearchIdBytes();
  }
  /**
   * Protobuf type {@code clarifai.api.FeedbackInfo}
   */
  public  static final class FeedbackInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:clarifai.api.FeedbackInfo)
      FeedbackInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FeedbackInfo.newBuilder() to construct.
    private FeedbackInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FeedbackInfo() {
      endUserId_ = "";
      sessionId_ = "";
      eventType_ = 0;
      outputId_ = "";
      searchId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FeedbackInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              endUserId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sessionId_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              eventType_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              outputId_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              searchId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return clarifai2.internal.grpc.api.Feedback.internal_static_clarifai_api_FeedbackInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return clarifai2.internal.grpc.api.Feedback.internal_static_clarifai_api_FeedbackInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              clarifai2.internal.grpc.api.Feedback.FeedbackInfo.class, clarifai2.internal.grpc.api.Feedback.FeedbackInfo.Builder.class);
    }

    public static final int END_USER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object endUserId_;
    /**
     * <code>string end_user_id = 1;</code>
     */
    public java.lang.String getEndUserId() {
      java.lang.Object ref = endUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endUserId_ = s;
        return s;
      }
    }
    /**
     * <code>string end_user_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEndUserIdBytes() {
      java.lang.Object ref = endUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSION_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object sessionId_;
    /**
     * <code>string session_id = 2;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      }
    }
    /**
     * <code>string session_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_TYPE_FIELD_NUMBER = 3;
    private int eventType_;
    /**
     * <code>.clarifai.api.EventType event_type = 3;</code>
     */
    public int getEventTypeValue() {
      return eventType_;
    }
    /**
     * <code>.clarifai.api.EventType event_type = 3;</code>
     */
    public clarifai2.internal.grpc.api.Feedback.EventType getEventType() {
      clarifai2.internal.grpc.api.Feedback.EventType result = clarifai2.internal.grpc.api.Feedback.EventType.valueOf(eventType_);
      return result == null ? clarifai2.internal.grpc.api.Feedback.EventType.UNRECOGNIZED : result;
    }

    public static final int OUTPUT_ID_FIELD_NUMBER = 4;
    private volatile java.lang.Object outputId_;
    /**
     * <code>string output_id = 4;</code>
     */
    public java.lang.String getOutputId() {
      java.lang.Object ref = outputId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outputId_ = s;
        return s;
      }
    }
    /**
     * <code>string output_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOutputIdBytes() {
      java.lang.Object ref = outputId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outputId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEARCH_ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object searchId_;
    /**
     * <code>string search_id = 5;</code>
     */
    public java.lang.String getSearchId() {
      java.lang.Object ref = searchId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        searchId_ = s;
        return s;
      }
    }
    /**
     * <code>string search_id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSearchIdBytes() {
      java.lang.Object ref = searchId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        searchId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEndUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, endUserId_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sessionId_);
      }
      if (eventType_ != clarifai2.internal.grpc.api.Feedback.EventType.undefined.getNumber()) {
        output.writeEnum(3, eventType_);
      }
      if (!getOutputIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, outputId_);
      }
      if (!getSearchIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, searchId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEndUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, endUserId_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sessionId_);
      }
      if (eventType_ != clarifai2.internal.grpc.api.Feedback.EventType.undefined.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, eventType_);
      }
      if (!getOutputIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, outputId_);
      }
      if (!getSearchIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, searchId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof clarifai2.internal.grpc.api.Feedback.FeedbackInfo)) {
        return super.equals(obj);
      }
      clarifai2.internal.grpc.api.Feedback.FeedbackInfo other = (clarifai2.internal.grpc.api.Feedback.FeedbackInfo) obj;

      boolean result = true;
      result = result && getEndUserId()
          .equals(other.getEndUserId());
      result = result && getSessionId()
          .equals(other.getSessionId());
      result = result && eventType_ == other.eventType_;
      result = result && getOutputId()
          .equals(other.getOutputId());
      result = result && getSearchId()
          .equals(other.getSearchId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + END_USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getEndUserId().hashCode();
      hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
      hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + eventType_;
      hash = (37 * hash) + OUTPUT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getOutputId().hashCode();
      hash = (37 * hash) + SEARCH_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSearchId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static clarifai2.internal.grpc.api.Feedback.FeedbackInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.Feedback.FeedbackInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Feedback.FeedbackInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.Feedback.FeedbackInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Feedback.FeedbackInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.Feedback.FeedbackInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Feedback.FeedbackInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.Feedback.FeedbackInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Feedback.FeedbackInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.Feedback.FeedbackInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.Feedback.FeedbackInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.Feedback.FeedbackInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(clarifai2.internal.grpc.api.Feedback.FeedbackInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code clarifai.api.FeedbackInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:clarifai.api.FeedbackInfo)
        clarifai2.internal.grpc.api.Feedback.FeedbackInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return clarifai2.internal.grpc.api.Feedback.internal_static_clarifai_api_FeedbackInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return clarifai2.internal.grpc.api.Feedback.internal_static_clarifai_api_FeedbackInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                clarifai2.internal.grpc.api.Feedback.FeedbackInfo.class, clarifai2.internal.grpc.api.Feedback.FeedbackInfo.Builder.class);
      }

      // Construct using clarifai2.internal.grpc.api.Feedback.FeedbackInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        endUserId_ = "";

        sessionId_ = "";

        eventType_ = 0;

        outputId_ = "";

        searchId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return clarifai2.internal.grpc.api.Feedback.internal_static_clarifai_api_FeedbackInfo_descriptor;
      }

      public clarifai2.internal.grpc.api.Feedback.FeedbackInfo getDefaultInstanceForType() {
        return clarifai2.internal.grpc.api.Feedback.FeedbackInfo.getDefaultInstance();
      }

      public clarifai2.internal.grpc.api.Feedback.FeedbackInfo build() {
        clarifai2.internal.grpc.api.Feedback.FeedbackInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public clarifai2.internal.grpc.api.Feedback.FeedbackInfo buildPartial() {
        clarifai2.internal.grpc.api.Feedback.FeedbackInfo result = new clarifai2.internal.grpc.api.Feedback.FeedbackInfo(this);
        result.endUserId_ = endUserId_;
        result.sessionId_ = sessionId_;
        result.eventType_ = eventType_;
        result.outputId_ = outputId_;
        result.searchId_ = searchId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof clarifai2.internal.grpc.api.Feedback.FeedbackInfo) {
          return mergeFrom((clarifai2.internal.grpc.api.Feedback.FeedbackInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(clarifai2.internal.grpc.api.Feedback.FeedbackInfo other) {
        if (other == clarifai2.internal.grpc.api.Feedback.FeedbackInfo.getDefaultInstance()) return this;
        if (!other.getEndUserId().isEmpty()) {
          endUserId_ = other.endUserId_;
          onChanged();
        }
        if (!other.getSessionId().isEmpty()) {
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.eventType_ != 0) {
          setEventTypeValue(other.getEventTypeValue());
        }
        if (!other.getOutputId().isEmpty()) {
          outputId_ = other.outputId_;
          onChanged();
        }
        if (!other.getSearchId().isEmpty()) {
          searchId_ = other.searchId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        clarifai2.internal.grpc.api.Feedback.FeedbackInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (clarifai2.internal.grpc.api.Feedback.FeedbackInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object endUserId_ = "";
      /**
       * <code>string end_user_id = 1;</code>
       */
      public java.lang.String getEndUserId() {
        java.lang.Object ref = endUserId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          endUserId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string end_user_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEndUserIdBytes() {
        java.lang.Object ref = endUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string end_user_id = 1;</code>
       */
      public Builder setEndUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        endUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string end_user_id = 1;</code>
       */
      public Builder clearEndUserId() {
        
        endUserId_ = getDefaultInstance().getEndUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string end_user_id = 1;</code>
       */
      public Builder setEndUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        endUserId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sessionId_ = "";
      /**
       * <code>string session_id = 2;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string session_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string session_id = 2;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string session_id = 2;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>string session_id = 2;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionId_ = value;
        onChanged();
        return this;
      }

      private int eventType_ = 0;
      /**
       * <code>.clarifai.api.EventType event_type = 3;</code>
       */
      public int getEventTypeValue() {
        return eventType_;
      }
      /**
       * <code>.clarifai.api.EventType event_type = 3;</code>
       */
      public Builder setEventTypeValue(int value) {
        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.clarifai.api.EventType event_type = 3;</code>
       */
      public clarifai2.internal.grpc.api.Feedback.EventType getEventType() {
        clarifai2.internal.grpc.api.Feedback.EventType result = clarifai2.internal.grpc.api.Feedback.EventType.valueOf(eventType_);
        return result == null ? clarifai2.internal.grpc.api.Feedback.EventType.UNRECOGNIZED : result;
      }
      /**
       * <code>.clarifai.api.EventType event_type = 3;</code>
       */
      public Builder setEventType(clarifai2.internal.grpc.api.Feedback.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        eventType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.clarifai.api.EventType event_type = 3;</code>
       */
      public Builder clearEventType() {
        
        eventType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object outputId_ = "";
      /**
       * <code>string output_id = 4;</code>
       */
      public java.lang.String getOutputId() {
        java.lang.Object ref = outputId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          outputId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string output_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOutputIdBytes() {
        java.lang.Object ref = outputId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          outputId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string output_id = 4;</code>
       */
      public Builder setOutputId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        outputId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string output_id = 4;</code>
       */
      public Builder clearOutputId() {
        
        outputId_ = getDefaultInstance().getOutputId();
        onChanged();
        return this;
      }
      /**
       * <code>string output_id = 4;</code>
       */
      public Builder setOutputIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        outputId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object searchId_ = "";
      /**
       * <code>string search_id = 5;</code>
       */
      public java.lang.String getSearchId() {
        java.lang.Object ref = searchId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          searchId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string search_id = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSearchIdBytes() {
        java.lang.Object ref = searchId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          searchId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string search_id = 5;</code>
       */
      public Builder setSearchId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        searchId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string search_id = 5;</code>
       */
      public Builder clearSearchId() {
        
        searchId_ = getDefaultInstance().getSearchId();
        onChanged();
        return this;
      }
      /**
       * <code>string search_id = 5;</code>
       */
      public Builder setSearchIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        searchId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:clarifai.api.FeedbackInfo)
    }

    // @@protoc_insertion_point(class_scope:clarifai.api.FeedbackInfo)
    private static final clarifai2.internal.grpc.api.Feedback.FeedbackInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new clarifai2.internal.grpc.api.Feedback.FeedbackInfo();
    }

    public static clarifai2.internal.grpc.api.Feedback.FeedbackInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FeedbackInfo>
        PARSER = new com.google.protobuf.AbstractParser<FeedbackInfo>() {
      public FeedbackInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeedbackInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FeedbackInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FeedbackInfo> getParserForType() {
      return PARSER;
    }

    public clarifai2.internal.grpc.api.Feedback.FeedbackInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clarifai_api_FeedbackInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clarifai_api_FeedbackInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!proto/clarifai/api/feedback.proto\022\014cla" +
      "rifai.api\"\212\001\n\014FeedbackInfo\022\023\n\013end_user_i" +
      "d\030\001 \001(\t\022\022\n\nsession_id\030\002 \001(\t\022+\n\nevent_typ" +
      "e\030\003 \001(\0162\027.clarifai.api.EventType\022\021\n\toutp" +
      "ut_id\030\004 \001(\t\022\021\n\tsearch_id\030\005 \001(\t*<\n\tEventT" +
      "ype\022\r\n\tundefined\020\000\022\020\n\014search_click\020\001\022\016\n\n" +
      "annotation\020\002BA\n\033clarifai2.internal.grpc." +
      "apiZ\003api\242\002\004CAIP\302\002\001_\312\002\021Clarifai\\Internalb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_clarifai_api_FeedbackInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_clarifai_api_FeedbackInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clarifai_api_FeedbackInfo_descriptor,
        new java.lang.String[] { "EndUserId", "SessionId", "EventType", "OutputId", "SearchId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
