// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/focus.proto

package clarifai2.internal.grpc.api;

public final class FocusOuterClass {
  private FocusOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FocusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:clarifai.api.Focus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float density = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    float getDensity();

    /**
     * <code>float value = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    float getValue();
  }
  /**
   * Protobuf type {@code clarifai.api.Focus}
   */
  public  static final class Focus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:clarifai.api.Focus)
      FocusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Focus.newBuilder() to construct.
    private Focus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Focus() {
      density_ = 0F;
      value_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Focus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              density_ = input.readFloat();
              break;
            }
            case 21: {

              value_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return clarifai2.internal.grpc.api.FocusOuterClass.internal_static_clarifai_api_Focus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return clarifai2.internal.grpc.api.FocusOuterClass.internal_static_clarifai_api_Focus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              clarifai2.internal.grpc.api.FocusOuterClass.Focus.class, clarifai2.internal.grpc.api.FocusOuterClass.Focus.Builder.class);
    }

    public static final int DENSITY_FIELD_NUMBER = 1;
    private float density_;
    /**
     * <code>float density = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    public float getDensity() {
      return density_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private float value_;
    /**
     * <code>float value = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    public float getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (density_ != 0F) {
        output.writeFloat(1, density_);
      }
      if (value_ != 0F) {
        output.writeFloat(2, value_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (density_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, density_);
      }
      if (value_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof clarifai2.internal.grpc.api.FocusOuterClass.Focus)) {
        return super.equals(obj);
      }
      clarifai2.internal.grpc.api.FocusOuterClass.Focus other = (clarifai2.internal.grpc.api.FocusOuterClass.Focus) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getDensity())
          == java.lang.Float.floatToIntBits(
              other.getDensity()));
      result = result && (
          java.lang.Float.floatToIntBits(getValue())
          == java.lang.Float.floatToIntBits(
              other.getValue()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DENSITY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDensity());
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getValue());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static clarifai2.internal.grpc.api.FocusOuterClass.Focus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.FocusOuterClass.Focus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.FocusOuterClass.Focus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.FocusOuterClass.Focus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.FocusOuterClass.Focus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clarifai2.internal.grpc.api.FocusOuterClass.Focus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.FocusOuterClass.Focus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.FocusOuterClass.Focus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.FocusOuterClass.Focus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.FocusOuterClass.Focus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static clarifai2.internal.grpc.api.FocusOuterClass.Focus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clarifai2.internal.grpc.api.FocusOuterClass.Focus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(clarifai2.internal.grpc.api.FocusOuterClass.Focus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code clarifai.api.Focus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:clarifai.api.Focus)
        clarifai2.internal.grpc.api.FocusOuterClass.FocusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return clarifai2.internal.grpc.api.FocusOuterClass.internal_static_clarifai_api_Focus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return clarifai2.internal.grpc.api.FocusOuterClass.internal_static_clarifai_api_Focus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                clarifai2.internal.grpc.api.FocusOuterClass.Focus.class, clarifai2.internal.grpc.api.FocusOuterClass.Focus.Builder.class);
      }

      // Construct using clarifai2.internal.grpc.api.FocusOuterClass.Focus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        density_ = 0F;

        value_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return clarifai2.internal.grpc.api.FocusOuterClass.internal_static_clarifai_api_Focus_descriptor;
      }

      public clarifai2.internal.grpc.api.FocusOuterClass.Focus getDefaultInstanceForType() {
        return clarifai2.internal.grpc.api.FocusOuterClass.Focus.getDefaultInstance();
      }

      public clarifai2.internal.grpc.api.FocusOuterClass.Focus build() {
        clarifai2.internal.grpc.api.FocusOuterClass.Focus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public clarifai2.internal.grpc.api.FocusOuterClass.Focus buildPartial() {
        clarifai2.internal.grpc.api.FocusOuterClass.Focus result = new clarifai2.internal.grpc.api.FocusOuterClass.Focus(this);
        result.density_ = density_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof clarifai2.internal.grpc.api.FocusOuterClass.Focus) {
          return mergeFrom((clarifai2.internal.grpc.api.FocusOuterClass.Focus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(clarifai2.internal.grpc.api.FocusOuterClass.Focus other) {
        if (other == clarifai2.internal.grpc.api.FocusOuterClass.Focus.getDefaultInstance()) return this;
        if (other.getDensity() != 0F) {
          setDensity(other.getDensity());
        }
        if (other.getValue() != 0F) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        clarifai2.internal.grpc.api.FocusOuterClass.Focus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (clarifai2.internal.grpc.api.FocusOuterClass.Focus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float density_ ;
      /**
       * <code>float density = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
       */
      public float getDensity() {
        return density_;
      }
      /**
       * <code>float density = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
       */
      public Builder setDensity(float value) {
        
        density_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float density = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
       */
      public Builder clearDensity() {
        
        density_ = 0F;
        onChanged();
        return this;
      }

      private float value_ ;
      /**
       * <code>float value = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
       */
      public float getValue() {
        return value_;
      }
      /**
       * <code>float value = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
       */
      public Builder setValue(float value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float value = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
       */
      public Builder clearValue() {
        
        value_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:clarifai.api.Focus)
    }

    // @@protoc_insertion_point(class_scope:clarifai.api.Focus)
    private static final clarifai2.internal.grpc.api.FocusOuterClass.Focus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new clarifai2.internal.grpc.api.FocusOuterClass.Focus();
    }

    public static clarifai2.internal.grpc.api.FocusOuterClass.Focus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Focus>
        PARSER = new com.google.protobuf.AbstractParser<Focus>() {
      public Focus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Focus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Focus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Focus> getParserForType() {
      return PARSER;
    }

    public clarifai2.internal.grpc.api.FocusOuterClass.Focus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clarifai_api_Focus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clarifai_api_Focus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036proto/clarifai/api/focus.proto\022\014clarif" +
      "ai.api\032)proto/clarifai/api/utils/extensi" +
      "ons.proto\"3\n\005Focus\022\025\n\007density\030\001 \001(\002B\004\200\265\030" +
      "\001\022\023\n\005value\030\002 \001(\002B\004\200\265\030\001BA\n\033clarifai2.inte" +
      "rnal.grpc.apiZ\003api\242\002\004CAIP\302\002\001_\312\002\021Clarifai" +
      "\\Internalb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          clarifai2.internal.grpc.api.utils.Extensions.getDescriptor(),
        }, assigner);
    internal_static_clarifai_api_Focus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_clarifai_api_Focus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clarifai_api_Focus_descriptor,
        new java.lang.String[] { "Density", "Value", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(clarifai2.internal.grpc.api.utils.Extensions.clShowIfEmpty);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    clarifai2.internal.grpc.api.utils.Extensions.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
