// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/usage_interval_type.proto

package clarifai2.internal.grpc.api;

public final class UsageIntervalTypeOuterClass {
  private UsageIntervalTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code clarifai.api.UsageIntervalType}
   */
  public enum UsageIntervalType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>undef = 0;</code>
     */
    undef(0),
    /**
     * <code>day = 1;</code>
     */
    day(1),
    /**
     * <code>month = 2;</code>
     */
    month(2),
    /**
     * <code>year = 3;</code>
     */
    year(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>undef = 0;</code>
     */
    public static final int undef_VALUE = 0;
    /**
     * <code>day = 1;</code>
     */
    public static final int day_VALUE = 1;
    /**
     * <code>month = 2;</code>
     */
    public static final int month_VALUE = 2;
    /**
     * <code>year = 3;</code>
     */
    public static final int year_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UsageIntervalType valueOf(int value) {
      return forNumber(value);
    }

    public static UsageIntervalType forNumber(int value) {
      switch (value) {
        case 0: return undef;
        case 1: return day;
        case 2: return month;
        case 3: return year;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UsageIntervalType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UsageIntervalType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UsageIntervalType>() {
            public UsageIntervalType findValueByNumber(int number) {
              return UsageIntervalType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return clarifai2.internal.grpc.api.UsageIntervalTypeOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final UsageIntervalType[] VALUES = values();

    public static UsageIntervalType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UsageIntervalType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:clarifai.api.UsageIntervalType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,proto/clarifai/api/usage_interval_type" +
      ".proto\022\014clarifai.api*<\n\021UsageIntervalTyp" +
      "e\022\t\n\005undef\020\000\022\007\n\003day\020\001\022\t\n\005month\020\002\022\010\n\004year" +
      "\020\003BA\n\033clarifai2.internal.grpc.apiZ\003api\242\002" +
      "\004CAIP\302\002\001_\312\002\021Clarifai\\Internalb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
