// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/utils/extensions.proto

package clarifai2.internal.grpc.api.utils;

public final class Extensions {
  private Extensions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(clarifai2.internal.grpc.api.utils.Extensions.clShowIfEmpty);
    registry.add(clarifai2.internal.grpc.api.utils.Extensions.clMoretags);
    registry.add(clarifai2.internal.grpc.api.utils.Extensions.clDefaultFloat);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int CL_SHOW_IF_EMPTY_FIELD_NUMBER = 50000;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> clShowIfEmpty = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int CL_MORETAGS_FIELD_NUMBER = 50001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> clMoretags = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int CL_DEFAULT_FLOAT_FIELD_NUMBER = 50010;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Float> clDefaultFloat = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Float.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)proto/clarifai/api/utils/extensions.pr" +
      "oto\022\022clarifai.api.utils\032 google/protobuf" +
      "/descriptor.proto:9\n\020cl_show_if_empty\022\035." +
      "google.protobuf.FieldOptions\030\320\206\003 \001(\010:4\n\013" +
      "cl_moretags\022\035.google.protobuf.FieldOptio" +
      "ns\030\321\206\003 \001(\t:9\n\020cl_default_float\022\035.google." +
      "protobuf.FieldOptions\030\332\206\003 \001(\002BO\n!clarifa" +
      "i2.internal.grpc.api.utilsZ\005utils\242\002\004CAIP" +
      "\302\002\001_\312\002\027Clarifai\\Internal\\Utilsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    clShowIfEmpty.internalInit(descriptor.getExtensions().get(0));
    clMoretags.internalInit(descriptor.getExtensions().get(1));
    clDefaultFloat.internalInit(descriptor.getExtensions().get(2));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
